# Generated by Django 3.2.7 on 2021-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210920_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(max_length=100),
        ),
    ]
