# Generated by Django 3.2.7 on 2021-09-22 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
