# Generated by Django 3.2.7 on 2021-09-24 15:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.catagory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.subcatagory'),
        ),
    ]
