# Generated by Django 3.2.7 on 2021-09-24 15:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210924_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=100, unique=True))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'product variation option',
                'verbose_name_plural': 'product variations options',
            },
        ),
        migrations.CreateModel(
            name='ProductVariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variation_value', models.CharField(max_length=100)),
                ('product_variation_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productvariationsoptions')),
            ],
        ),
    ]
