# Generated by Django 3.2.7 on 2021-09-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productvariationsoptions_productvariationvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_string', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'product inventory',
                'verbose_name_plural': 'product inventories',
            },
        ),
    ]
