# Generated by Django 3.2.7 on 2021-09-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210925_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariationsoptions',
            name='slug',
        ),
    ]
