# Generated by Django 3.2.7 on 2021-09-27 14:36

import cloudinary.models
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2021, 9, 27, 14, 36, 21, 935079, tzinfo=utc), max_length=255, verbose_name='product/image'),
            preserve_default=False,
        ),
    ]
