# Generated by Django 3.2.7 on 2021-09-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210927_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.product'),
        ),
    ]
