# Generated by Django 3.2.7 on 2021-09-28 05:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
