# Generated by Django 3.2.7 on 2021-09-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
